### ISSUE TITLE
Non-clickable window when debugging on mac os

### ISSUE THREAD

**Issue by ufgo** [defold/defold#6709]
In most cases, when debugging is started, it will not respond to clicks. To solve the problem, you need to switch to another window and then return to the debug window.

**To Reproduce:**
1. Go to 'Debug>Start/Attach'
2. Click on 'window'
3. Window is not clickable

**Expected behavior:**
Debug version must react to click

**Defold version:**
  - Version 1.3.2

**Platforms:**
 - Platforms:  macOS 12.5.1

**Comment by JCash** [comment]
Thanks!
Does this project have native extensions?

Nowadays we do build the macOS version on a macOS machine, so it shouldn't really differ much from our vanilla engine. But perhaps we have some nuanced difference between the two.

**Comment by ufgo** [comment]
![java_1uj54h9YmP](https://user-images.githubusercontent.com/21050233/173776789-61bfb312-bd9e-48ea-aa1d-8d42e8736bd1.png)
thats all what i use in my project

**Comment by JCash** [comment]
Thanks.
The important part was knowing if the executable was built on the cloud server or not.
Now we know where to look for discrepancies.

**Comment by AGulev** [comment]
it should be fixed in 1.3.5

**Comment by britzl** [comment]
According to the user this issue persists in 1.3.6 beta. Reopening.

@ufgo does this happen with any project? Or only one with some extensions?

**Comment by ufgo** [comment]
this problem remains even without using extensions

**Comment by ufgo** [comment]
https://user-images.githubusercontent.com/21050233/189599923-291a1169-3cdd-4293-abd9-db053c56371f.mov


in attached video you can see i clicked mouse but nothing happened

**Comment by Lerg** [comment]
Sometimes after the project is build and run from the editor on macOS, it only responds to every third click or so. Rerunning the project fixes the issue. E.g. I have to click a button in the game three times for it to work.

**Comment by AGulev** [comment]
is it possible this one is related https://github.com/defold/defold/issues/7176 ?

**Comment by AGulev** [comment]
it seems like sometimes app starts unfocused 
<img width="744" alt="image" src="https://github.com/defold/defold/assets/2209596/3da617e7-2207-4a33-82da-e3b1e1bbb6da">

Click to some other app and then click to the defold app helps: 
<img width="802" alt="image" src="https://github.com/defold/defold/assets/2209596/0c53a445-4363-4caa-b241-54250b48559d">

**Comment by AGulev** [comment]
it's easier to repo when build and run using f5
it seems like editor does something that changes focus to it:

![image](https://github.com/defold/defold/assets/2209596/805fc2d7-4050-433b-9747-aecb202e6c67)

**Comment by AGulev** [comment]
Screen Recording 2023-07-13 at 15.24.25

**Comment by AGulev** [comment]
https://github.com/defold/defold/assets/2209596/25d9d793-6228-4b9f-bd47-59ef99474052
