### ISSUE TITLE
Show read only image size when sprite is selected

### ISSUE THREAD

**Issue by subsoap** [defold/defold#6785]
![2022-07-07 13_17_14-general - Discord](https://user-images.githubusercontent.com/409170/177864060-b46dcd8b-59f1-41fd-8dc1-e52eea40a1e8.png)
![2022-07-07 13_17_00-general - Discord](https://user-images.githubusercontent.com/409170/177864065-9bac9575-5f78-47d9-a1fd-849eb51d0e6a.png)

Add an "Image Size" below the Image field when selecting a sprite. This kind of context information can be useful/convenient to devs. For example, I want to make a collision object here the same size of the sprite image but I don't see that size where I'm making the collision object I have to look elsewhere.

**Comment by quangson91** [comment]
Hi @britzl @matgis 
I also want to work on this issue.

Here is my idea before code.

**Design**
![image-size-design](https://github.com/defold/defold/assets/6185205/248b91b5-3698-4821-9477-94ebcdfa9f8e)

We will add new `image size` info. Which will display the size of current `Default animation` sprite.

**Code**

It seems the properties is generated at `(g/defnk produce-component-properties` (game_object.clj)

So my idea is add one property that  is a size of current `Default animation`. (the property that look like `:position` property) <--- _But I need help here. Where is the exactly code to add a new property._


How do you think?

**Comment by matgis** [comment]
You should actually only need to add a new `(property ...)` to the `defnode` for the Sprite component. Look at the implementation for the existing `size` property that will show the size from the selected animation if the `size-mode` is set to auto here: https://github.com/defold/defold/blob/dev/editor/src/clj/editor/sprite.clj#L491-L500

**Comment by matgis** [comment]
The `(value (g/fnk [manual-size size-mode animation] ...)` means we evaluate the properties, inputs, or outputs `manual-size`, `size-mode`, and `animation` on the node itself and use them to produce the result that will be displayed in the property editor for the property.

**Comment by quangson91** [comment]
Thank you. I will check it more

**Comment by quangson91** [comment]
@matgis 
I think this issue is already fixed, right ?
From the screenshot in the description, I think it is old version.
But for the new version, we already have size-mode & size.
So, I think this issue is already fixed.

Am I misunderstood anything?

**Comment by matgis** [comment]
Hmm. Looking at it more, I think you may be right. That's an old screenshot from before we had a Size field.

Initially I read it as they wanted to see the original Image Size as a separate read-only field, so they could still see it in case they had specified a manual size. But maybe it is not needed? For the collision shape example, you'd want to have the collision shape be the same size as the manual size if you had that set.

@subsoap What do you think? Should we close this issue now that we have the Size property visible in the property editor?

**Comment by britzl** [comment]
> What do you think? Should we close this issue now that we have the Size property visible in the property editor?

I think it is ok to close this feature request to be honest. I guess the only reason to still show the size in a separate field is in the case that you've set the Size Mode to manual (for 9-slice). In that case you do not know the original size of the image, but it is hardly a big deal.

**Comment by AGulev** [comment]
![CleanShot 2024-03-10 at 15 44 16@2x](https://github.com/defold/defold/assets/2209596/22b647cd-05f9-4b5a-9fa9-ee3c2fe897d3)
that's how it looks now when `auto` size picked for sprite

**Comment by AGulev** [comment]
Closed because now we have `Size` property
Feel free to reopen if it's not enough
